/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlimentsRouteImport } from './routes/aliments'
import { Route as CalculateursRouteImport } from './routes/calculateurs'
import { Route as MaladiesRouteImport } from './routes/maladies'
import { Route as RegimesRouteImport } from './routes/regimes'
import { Route as AlimentsIdRouteImport } from './routes/aliments.$id'
import { Route as CalculateursIndexRouteImport } from './routes/calculateurs.index'
import { Route as CalculateursDfgRouteImport } from './routes/calculateurs.dfg'
import { Route as MaladiesIndexRouteImport } from './routes/maladies.index'
import { Route as MaladiesSlugRouteImport } from './routes/maladies.$slug'
import { Route as RegimesSlugRouteImport } from './routes/regimes.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlimentsRoute = AlimentsRouteImport.update({
  id: '/aliments',
  path: '/aliments',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculateursRoute = CalculateursRouteImport.update({
  id: '/calculateurs',
  path: '/calculateurs',
  getParentRoute: () => rootRouteImport,
} as any)
const MaladiesRoute = MaladiesRouteImport.update({
  id: '/maladies',
  path: '/maladies',
  getParentRoute: () => rootRouteImport,
} as any)
const RegimesRoute = RegimesRouteImport.update({
  id: '/regimes',
  path: '/regimes',
  getParentRoute: () => rootRouteImport,
} as any)
const AlimentsIdRoute = AlimentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AlimentsRoute,
} as any)
const CalculateursIndexRoute = CalculateursIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CalculateursRoute,
} as any)
const CalculateursDfgRoute = CalculateursDfgRouteImport.update({
  id: '/dfg',
  path: '/dfg',
  getParentRoute: () => CalculateursRoute,
} as any)
const MaladiesIndexRoute = MaladiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MaladiesRoute,
} as any)
const MaladiesSlugRoute = MaladiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MaladiesRoute,
} as any)
const RegimesSlugRoute = RegimesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RegimesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aliments': typeof AlimentsRouteWithChildren
  '/calculateurs': typeof CalculateursRouteWithChildren
  '/maladies': typeof MaladiesRouteWithChildren
  '/regimes': typeof RegimesRouteWithChildren
  '/aliments/$id': typeof AlimentsIdRoute
  '/calculateurs/dfg': typeof CalculateursDfgRoute
  '/maladies/$slug': typeof MaladiesSlugRoute
  '/regimes/$slug': typeof RegimesSlugRoute
  '/calculateurs/': typeof CalculateursIndexRoute
  '/maladies/': typeof MaladiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aliments': typeof AlimentsRouteWithChildren
  '/regimes': typeof RegimesRouteWithChildren
  '/aliments/$id': typeof AlimentsIdRoute
  '/calculateurs/dfg': typeof CalculateursDfgRoute
  '/maladies/$slug': typeof MaladiesSlugRoute
  '/regimes/$slug': typeof RegimesSlugRoute
  '/calculateurs': typeof CalculateursIndexRoute
  '/maladies': typeof MaladiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aliments': typeof AlimentsRouteWithChildren
  '/calculateurs': typeof CalculateursRouteWithChildren
  '/maladies': typeof MaladiesRouteWithChildren
  '/regimes': typeof RegimesRouteWithChildren
  '/aliments/$id': typeof AlimentsIdRoute
  '/calculateurs/dfg': typeof CalculateursDfgRoute
  '/maladies/$slug': typeof MaladiesSlugRoute
  '/regimes/$slug': typeof RegimesSlugRoute
  '/calculateurs/': typeof CalculateursIndexRoute
  '/maladies/': typeof MaladiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aliments'
    | '/calculateurs'
    | '/maladies'
    | '/regimes'
    | '/aliments/$id'
    | '/calculateurs/dfg'
    | '/maladies/$slug'
    | '/regimes/$slug'
    | '/calculateurs/'
    | '/maladies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aliments'
    | '/regimes'
    | '/aliments/$id'
    | '/calculateurs/dfg'
    | '/maladies/$slug'
    | '/regimes/$slug'
    | '/calculateurs'
    | '/maladies'
  id:
    | '__root__'
    | '/'
    | '/aliments'
    | '/calculateurs'
    | '/maladies'
    | '/regimes'
    | '/aliments/$id'
    | '/calculateurs/dfg'
    | '/maladies/$slug'
    | '/regimes/$slug'
    | '/calculateurs/'
    | '/maladies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlimentsRoute: typeof AlimentsRouteWithChildren
  CalculateursRoute: typeof CalculateursRouteWithChildren
  MaladiesRoute: typeof MaladiesRouteWithChildren
  RegimesRoute: typeof RegimesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aliments': {
      id: '/aliments'
      path: '/aliments'
      fullPath: '/aliments'
      preLoaderRoute: typeof AlimentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculateurs': {
      id: '/calculateurs'
      path: '/calculateurs'
      fullPath: '/calculateurs'
      preLoaderRoute: typeof CalculateursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maladies': {
      id: '/maladies'
      path: '/maladies'
      fullPath: '/maladies'
      preLoaderRoute: typeof MaladiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regimes': {
      id: '/regimes'
      path: '/regimes'
      fullPath: '/regimes'
      preLoaderRoute: typeof RegimesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aliments/$id': {
      id: '/aliments/$id'
      path: '/$id'
      fullPath: '/aliments/$id'
      preLoaderRoute: typeof AlimentsIdRouteImport
      parentRoute: typeof AlimentsRoute
    }
    '/calculateurs/': {
      id: '/calculateurs/'
      path: '/'
      fullPath: '/calculateurs/'
      preLoaderRoute: typeof CalculateursIndexRouteImport
      parentRoute: typeof CalculateursRoute
    }
    '/calculateurs/dfg': {
      id: '/calculateurs/dfg'
      path: '/dfg'
      fullPath: '/calculateurs/dfg'
      preLoaderRoute: typeof CalculateursDfgRouteImport
      parentRoute: typeof CalculateursRoute
    }
    '/maladies/': {
      id: '/maladies/'
      path: '/'
      fullPath: '/maladies/'
      preLoaderRoute: typeof MaladiesIndexRouteImport
      parentRoute: typeof MaladiesRoute
    }
    '/maladies/$slug': {
      id: '/maladies/$slug'
      path: '/$slug'
      fullPath: '/maladies/$slug'
      preLoaderRoute: typeof MaladiesSlugRouteImport
      parentRoute: typeof MaladiesRoute
    }
    '/regimes/$slug': {
      id: '/regimes/$slug'
      path: '/$slug'
      fullPath: '/regimes/$slug'
      preLoaderRoute: typeof RegimesSlugRouteImport
      parentRoute: typeof RegimesRoute
    }
  }
}

interface AlimentsRouteChildren {
  AlimentsIdRoute: typeof AlimentsIdRoute
}

const AlimentsRouteChildren: AlimentsRouteChildren = {
  AlimentsIdRoute: AlimentsIdRoute,
}

const AlimentsRouteWithChildren = AlimentsRoute._addFileChildren(
  AlimentsRouteChildren,
)

interface CalculateursRouteChildren {
  CalculateursDfgRoute: typeof CalculateursDfgRoute
  CalculateursIndexRoute: typeof CalculateursIndexRoute
}

const CalculateursRouteChildren: CalculateursRouteChildren = {
  CalculateursDfgRoute: CalculateursDfgRoute,
  CalculateursIndexRoute: CalculateursIndexRoute,
}

const CalculateursRouteWithChildren = CalculateursRoute._addFileChildren(
  CalculateursRouteChildren,
)

interface MaladiesRouteChildren {
  MaladiesSlugRoute: typeof MaladiesSlugRoute
  MaladiesIndexRoute: typeof MaladiesIndexRoute
}

const MaladiesRouteChildren: MaladiesRouteChildren = {
  MaladiesSlugRoute: MaladiesSlugRoute,
  MaladiesIndexRoute: MaladiesIndexRoute,
}

const MaladiesRouteWithChildren = MaladiesRoute._addFileChildren(
  MaladiesRouteChildren,
)

interface RegimesRouteChildren {
  RegimesSlugRoute: typeof RegimesSlugRoute
}

const RegimesRouteChildren: RegimesRouteChildren = {
  RegimesSlugRoute: RegimesSlugRoute,
}

const RegimesRouteWithChildren =
  RegimesRoute._addFileChildren(RegimesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlimentsRoute: AlimentsRouteWithChildren,
  CalculateursRoute: CalculateursRouteWithChildren,
  MaladiesRoute: MaladiesRouteWithChildren,
  RegimesRoute: RegimesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
