/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegimesRouteImport } from './routes/regimes'
import { Route as RegimesSlugRouteImport } from './routes/regimes.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegimesRoute = RegimesRouteImport.update({
  id: '/regimes',
  path: '/regimes',
  getParentRoute: () => rootRouteImport,
} as any)
const RegimesSlugRoute = RegimesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RegimesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/regimes': typeof RegimesRouteWithChildren
  '/regimes/$slug': typeof RegimesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/regimes': typeof RegimesRouteWithChildren
  '/regimes/$slug': typeof RegimesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/regimes': typeof RegimesRouteWithChildren
  '/regimes/$slug': typeof RegimesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/regimes' | '/regimes/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/regimes' | '/regimes/$slug'
  id: '__root__' | '/' | '/regimes' | '/regimes/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegimesRoute: typeof RegimesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regimes': {
      id: '/regimes'
      path: '/regimes'
      fullPath: '/regimes'
      preLoaderRoute: typeof RegimesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regimes/$slug': {
      id: '/regimes/$slug'
      path: '/$slug'
      fullPath: '/regimes/$slug'
      preLoaderRoute: typeof RegimesSlugRouteImport
      parentRoute: typeof RegimesRoute
    }
  }
}

interface RegimesRouteChildren {
  RegimesSlugRoute: typeof RegimesSlugRoute
}

const RegimesRouteChildren: RegimesRouteChildren = {
  RegimesSlugRoute: RegimesSlugRoute,
}

const RegimesRouteWithChildren =
  RegimesRoute._addFileChildren(RegimesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegimesRoute: RegimesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
