/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlimentsRouteImport } from './routes/aliments'
import { Route as MaladiesRouteImport } from './routes/maladies'
import { Route as RegimesRouteImport } from './routes/regimes'
import { Route as MaladiesSlugRouteImport } from './routes/maladies.$slug'
import { Route as RegimesSlugRouteImport } from './routes/regimes.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlimentsRoute = AlimentsRouteImport.update({
  id: '/aliments',
  path: '/aliments',
  getParentRoute: () => rootRouteImport,
} as any)
const MaladiesRoute = MaladiesRouteImport.update({
  id: '/maladies',
  path: '/maladies',
  getParentRoute: () => rootRouteImport,
} as any)
const RegimesRoute = RegimesRouteImport.update({
  id: '/regimes',
  path: '/regimes',
  getParentRoute: () => rootRouteImport,
} as any)
const MaladiesSlugRoute = MaladiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MaladiesRoute,
} as any)
const RegimesSlugRoute = RegimesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RegimesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aliments': typeof AlimentsRoute
  '/maladies': typeof MaladiesRouteWithChildren
  '/regimes': typeof RegimesRouteWithChildren
  '/maladies/$slug': typeof MaladiesSlugRoute
  '/regimes/$slug': typeof RegimesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aliments': typeof AlimentsRoute
  '/maladies': typeof MaladiesRouteWithChildren
  '/regimes': typeof RegimesRouteWithChildren
  '/maladies/$slug': typeof MaladiesSlugRoute
  '/regimes/$slug': typeof RegimesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aliments': typeof AlimentsRoute
  '/maladies': typeof MaladiesRouteWithChildren
  '/regimes': typeof RegimesRouteWithChildren
  '/maladies/$slug': typeof MaladiesSlugRoute
  '/regimes/$slug': typeof RegimesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aliments'
    | '/maladies'
    | '/regimes'
    | '/maladies/$slug'
    | '/regimes/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aliments'
    | '/maladies'
    | '/regimes'
    | '/maladies/$slug'
    | '/regimes/$slug'
  id:
    | '__root__'
    | '/'
    | '/aliments'
    | '/maladies'
    | '/regimes'
    | '/maladies/$slug'
    | '/regimes/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlimentsRoute: typeof AlimentsRoute
  MaladiesRoute: typeof MaladiesRouteWithChildren
  RegimesRoute: typeof RegimesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aliments': {
      id: '/aliments'
      path: '/aliments'
      fullPath: '/aliments'
      preLoaderRoute: typeof AlimentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maladies': {
      id: '/maladies'
      path: '/maladies'
      fullPath: '/maladies'
      preLoaderRoute: typeof MaladiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regimes': {
      id: '/regimes'
      path: '/regimes'
      fullPath: '/regimes'
      preLoaderRoute: typeof RegimesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maladies/$slug': {
      id: '/maladies/$slug'
      path: '/$slug'
      fullPath: '/maladies/$slug'
      preLoaderRoute: typeof MaladiesSlugRouteImport
      parentRoute: typeof MaladiesRoute
    }
    '/regimes/$slug': {
      id: '/regimes/$slug'
      path: '/$slug'
      fullPath: '/regimes/$slug'
      preLoaderRoute: typeof RegimesSlugRouteImport
      parentRoute: typeof RegimesRoute
    }
  }
}

interface MaladiesRouteChildren {
  MaladiesSlugRoute: typeof MaladiesSlugRoute
}

const MaladiesRouteChildren: MaladiesRouteChildren = {
  MaladiesSlugRoute: MaladiesSlugRoute,
}

const MaladiesRouteWithChildren = MaladiesRoute._addFileChildren(
  MaladiesRouteChildren,
)

interface RegimesRouteChildren {
  RegimesSlugRoute: typeof RegimesSlugRoute
}

const RegimesRouteChildren: RegimesRouteChildren = {
  RegimesSlugRoute: RegimesSlugRoute,
}

const RegimesRouteWithChildren =
  RegimesRoute._addFileChildren(RegimesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlimentsRoute: AlimentsRoute,
  MaladiesRoute: MaladiesRouteWithChildren,
  RegimesRoute: RegimesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
